services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=todo-list'
      - 'POSTGRES_PASSWORD=2a6e005d7f'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
