spring.application.name=todo-list
spring.docker.compose.enabled=false


#Válido tanto pro local quanto pro supabase
spring.jpa.hibernate.ddl-auto=update

#Postgres Local
#spring.datasource.url=jdbc:postgresql://localhost:5432/
#spring.datasource.username=postgres
#spring.datasource.password=2a6e005d7f
#spring.jpa.show-sql=true

